<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jacob T.N. Young">

<title>Social Network Analysis for Crime Analysts - Closeness Centrality</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./snaca-centrality-betweenness.html" rel="next">
<link href="./snaca-centrality-degree.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./snaca-centrality-closeness.html">Closeness Centrality</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Social Network Analysis for Crime Analysts</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/jacobtnyoung/snaca-textbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./snaca-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Social Network Analysis for Crime Analysts</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./snaca-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Network Theory and Theory of Networks</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./snaca-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Network Data Collection</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./snaca-net-data-structures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Network Data Structures</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./snaca-net-description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Network Description</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./snaca-centrality-degree.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Degree Centrality</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./snaca-centrality-closeness.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Closeness Centrality</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./snaca-centrality-betweenness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Betweenness Centrality</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./snaca-bipartite.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bipartite Graphs/Two-Mode Networks</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./snaca-projection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projection</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#case-study-terror-networks-and-closeness" id="toc-case-study-terror-networks-and-closeness" class="nav-link active" data-scroll-target="#case-study-terror-networks-and-closeness">Case Study: Terror Networks and Closeness</a>
  <ul class="collapse">
  <li><a href="#closeness-centrality-terms" id="toc-closeness-centrality-terms" class="nav-link" data-scroll-target="#closeness-centrality-terms">Closeness Centrality Terms</a></li>
  </ul></li>
  <li><a href="#undirected-graphs" id="toc-undirected-graphs" class="nav-link" data-scroll-target="#undirected-graphs">Undirected Graphs</a>
  <ul class="collapse">
  <li><a href="#closeness-centrality" id="toc-closeness-centrality" class="nav-link" data-scroll-target="#closeness-centrality">Closeness Centrality</a></li>
  <li><a href="#standardization" id="toc-standardization" class="nav-link" data-scroll-target="#standardization">Standardization</a></li>
  <li><a href="#mean-closeness" id="toc-mean-closeness" class="nav-link" data-scroll-target="#mean-closeness">Mean Closeness</a></li>
  <li><a href="#closeness-centralization" id="toc-closeness-centralization" class="nav-link" data-scroll-target="#closeness-centralization">Closeness Centralization</a></li>
  </ul></li>
  <li><a href="#directed-graphs" id="toc-directed-graphs" class="nav-link" data-scroll-target="#directed-graphs">Directed Graphs</a>
  <ul class="collapse">
  <li><a href="#outdegree" id="toc-outdegree" class="nav-link" data-scroll-target="#outdegree">Outdegree</a></li>
  <li><a href="#mean-clonessness" id="toc-mean-clonessness" class="nav-link" data-scroll-target="#mean-clonessness">Mean Clonessness</a></li>
  <li><a href="#indegree" id="toc-indegree" class="nav-link" data-scroll-target="#indegree">Indegree</a></li>
  <li><a href="#conversion-to-undirected-graph" id="toc-conversion-to-undirected-graph" class="nav-link" data-scroll-target="#conversion-to-undirected-graph">Conversion to Undirected Graph</a></li>
  <li><a href="#closeness-centralization-1" id="toc-closeness-centralization-1" class="nav-link" data-scroll-target="#closeness-centralization-1">Closeness Centralization</a></li>
  </ul></li>
  <li><a href="#test-your-knowledge" id="toc-test-your-knowledge" class="nav-link" data-scroll-target="#test-your-knowledge">Test your Knowledge</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/jacobtnyoung/snaca-textbook/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Closeness Centrality</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>In the prior chapter, we examined the idea of “centrality” for nodes and “centralization” for graphs, focusing attention on the conceptual aspects of what it means to be <em>central</em> as well as the ways in which we can operationalize the concept using <em>degree centrality</em>. In this chapter we want to continue thinking about what it means to be central, but through a different conceptual lens: <strong>closeness</strong>. As a crime analyst, examining closeness centrality can provide crucial insights into the efficiency and influence of individuals within a group that may go beyond what you can glean from examining degree centrality. For instance, <span class="citation" data-cites="bright2015illuminating">Bright, Hughes, and Chalmers (<a href="references.html#ref-bright2015illuminating" role="doc-biblioref">2015</a>)</span> study of drug trafficking networks illustrates how closeness centrality played a pivotal role in understanding the structure and function of illicit organizations. In this study, <span class="citation" data-cites="bright2015illuminating">Bright, Hughes, and Chalmers (<a href="references.html#ref-bright2015illuminating" role="doc-biblioref">2015</a>)</span> examined an Australian drug trafficking network and found that individuals with higher closeness centrality were not necessarily the most visible or directly connected (in terms of degree centrality), but held critical positions because of their proximity to others in the network. These individuals could quickly access and disseminate information across the group, making them key actors in maintaining the flow of drugs, money, and communication. By identifying those with high closeness centrality, law enforcement was able to target individuals who had the potential to disrupt the network’s operations more effectively than simply targeting those with the most connections.</p>
<p>By the end of this chapter, you should be able to:</p>
<ul>
<li>Explain the conceptualization of “centrality” as it pertains to <em>closeness centrality</em>.</li>
<li>Calculate closeness centrality scores for a set of nodes.</li>
<li>Calculate a closeness centralization score for a graph.</li>
</ul>
<section id="case-study-terror-networks-and-closeness" class="level2">
<h2 class="anchored" data-anchor-id="case-study-terror-networks-and-closeness">Case Study: Terror Networks and Closeness</h2>
<p><span class="citation" data-cites="sageman2004understanding">Sageman (<a href="references.html#ref-sageman2004understanding" role="doc-biblioref">2004</a>)</span> studied global Islamist terrorist networks and demonstrated how individuals with high closeness centrality played a key role in maintaining the cohesion and communication efficiency within these decentralized groups. These key players, even though they may not have had the most direct connections (high degree centrality), were crucial in maintaining the operational efficiency of the network. By targeting those with high closeness centrality, counter-terrorism efforts were able to more effectively disrupt communication channels and reduce the operational capabilities of the group.</p>
<section id="closeness-centrality-terms" class="level3">
<h3 class="anchored" data-anchor-id="closeness-centrality-terms">Closeness Centrality Terms</h3>
<p>How <em>close</em> is a node to other nodes? <em>Closeness</em> centrality measures how near a node is to the other nodes in the network. That is, how “close” the nodes are. What we mean by “close” will differ based on whether the graph is undirected or directed. But the conceptual definition is the same. How close nodes are in a graph is based on the inverse of the distance of each node to every other node.</p>
<p>Terminology:</p>
<ul>
<li>A <strong>path</strong> is an edge or sequence of edges that connect two nodes.</li>
<li>A <strong>geodesic</strong> is the shortest path between two nodes.</li>
<li>The <strong>distance</strong>, <span class="math inline">\(d(n_i,n_j)\)</span>, is the length of the path between <em>i</em> and <em>j</em>.</li>
</ul>
<p>Another way of saying this is that if we know how “far apart” two nodes are (i.e.&nbsp;the distance), then we can take the inverse of that and know how “close” the nodes are to each other.</p>
</section>
</section>
<section id="undirected-graphs" class="level2">
<h2 class="anchored" data-anchor-id="undirected-graphs">Undirected Graphs</h2>
<section id="closeness-centrality" class="level3">
<h3 class="anchored" data-anchor-id="closeness-centrality">Closeness Centrality</h3>
<p>For an undirected binary graph, the closeness is:</p>
<p><span class="math display">\[C_C(n_i) = [\sum\limits_{j=1}^g d(n_i,n_j)]^{-1}\]</span></p>
<p>This reads as: Find the distance between two nodes <em>i</em> and <em>j</em>, <span class="math inline">\(d(n_i,n_j)\)</span>, sum them, and then take the inverse.</p>
<p>Another way to write this is as:</p>
<p><span class="math display">\[C_C(n_i) = [\sum\limits_{j=1}^g d(n_i,n_j)]^{-1} = \frac{1}{[\sum\limits_{j=1}^g d(n_i,n_j)]}\]</span></p>
<p>In words, the closeness is 1 divided by the sum of the distances (called the <em>reciprocal</em>).</p>
<p>To find the closeness centrality score, we need to first find the distances between each node. We can express these distances using a matrix, just like we did with the sociomatrix before.</p>
<p>Let’s take a look at this with some data. Recall our example network with Jen, Tom, Bob, Leaf, and Jim:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>How far is Jen from Tom? How far is Jen from Bob? In other words, how many edges do we count in going from Jen to Tom? From Jen to Bob?</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>For our graph, we want to first build a <em>distance matrix</em> which shows the value of the geodesic (i.e.&nbsp;shortest path) from <em>i</em> to <em>j</em>. We can do this by looking at each node and seeing the fewest steps that are needed to reach another node. We can see that Jen can reach Tom in 1 step (i.e.&nbsp;<span class="math inline">\(L_{Jen,Tom}\)</span>) and that Jen can reach Bob in 2 steps (i.e.&nbsp;<span class="math inline">\(L_{Jen,Tom}\)</span> &amp; <span class="math inline">\(L_{Tom,Bob}\)</span>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Since the graph is undirected, the distance matrix is symmetric about the diagonal (just like we saw with an adjacency matrix). That is, <span class="math inline">\(d(n_i,n_j) = d(n_j,n_i)\)</span>. This gives us:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Now, what about the rest of the distance matrix? If we follow what we did above for everyone else, then we get the following distance matrix:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Now, if we take the sum of the rows, this gives us <span class="math inline">\(\sum\limits_{j=1}^g d(n_i,n_j)\)</span>. Note that since the graph is undirected, the column sum would give us the same values. Since we have <span class="math inline">\(\sum\limits_{j=1}^g d(n_i,n_j)\)</span>, all we need to do now is take the reciprocal by dividing 1 by <span class="math inline">\(\sum\limits_{j=1}^g d(n_i,n_j)\)</span>:</p>
<p><span class="math display">\[C_C(n_i) =  \frac{1}{[\sum\limits_{j=1}^g d(n_i,n_j)]}\]</span></p>
<p>That gives us the closeness centrality score for each individual:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Node</th>
<th style="text-align: center;">Distance</th>
<th style="text-align: center;">Closeness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Jen</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">1/9 = 0.111</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tom</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">1/6 = 0.167</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Bob</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">1/5 = 0.200</td>
</tr>
<tr class="even">
<td style="text-align: center;">Leaf</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1/7 = 0.143</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Jim</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1/7 = 0.143</td>
</tr>
</tbody>
</table>
</section>
<section id="standardization" class="level3">
<h3 class="anchored" data-anchor-id="standardization">Standardization</h3>
<p>As discussed in the prior chapter, centrality measures are sensitive to the size of the graph, <em>g</em>. In the case of <em>closeness</em> centrality, having to sum over more nodes will push scores closer to zero. Think about it: if we added more rows and columns to our distance matrix, that will increase the denominator, making the quotient smaller. This means that we can’t compare closeness centrality scores across graphs of different sizes. <em>Solution</em>?</p>
<p>Standardize! If we want to compare nodes in different sized networks, then we just take into account the number of nodes and the maximum possible nodes to which <em>i</em> could be connected. In an undirected graph, this is <em>g-1</em>.</p>
<p>Thus, we can calculate a standardized closeness centrality for an undirected graph as:</p>
<p><span class="math display">\[C'_C(n_i) = [\sum\limits_{j=1}^g d(n_i,n_j)]^{-1} \times [g-1]\]</span></p>
<p>For this graph, the denominator, <em>g-1</em> is <span class="math inline">\(5 - 1 = 4\)</span>. Plugging that in we get: <span class="math inline">\(C'_C(n_i) = [\sum\limits_{j=1}^g d(n_i,n_j)]^{-1} \times 4\)</span>.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Node</th>
<th style="text-align: center;">Distance</th>
<th style="text-align: center;">Closeness</th>
<th style="text-align: center;">Standardized Closeness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Jen</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">1/9 = 0.111</td>
<td style="text-align: center;">0.111*4 = 0.444</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tom</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">1/6 = 0.167</td>
<td style="text-align: center;">0.167*4 = 0.668</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Bob</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">1/5 = 0.200</td>
<td style="text-align: center;">0.200*4 = 0.800</td>
</tr>
<tr class="even">
<td style="text-align: center;">Leaf</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1/7 = 0.143</td>
<td style="text-align: center;">0.143*4 = 0.572</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Jim</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1/7 = 0.143</td>
<td style="text-align: center;">0.143*4 = 0.572</td>
</tr>
</tbody>
</table>
<p>Standardization is particularly important with <em>closeness</em> centrality because of the sensitivity of the measure to the size of the network. Take for example, the following networks:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>The plot above shows two different graphs with the <em>raw</em> closeness centrality scores for two nodes. Note that they have the exact same score. Yet, would you say they are equally close to other nodes in the network? In other words, that their closeness to other nodes is the same?</p>
<p>When we standardize, we adjust for the size of the network:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Now, apply the same thing to the rest of the network:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="mean-closeness" class="level3">
<h3 class="anchored" data-anchor-id="mean-closeness">Mean Closeness</h3>
<p>We can examine the summary statistics for closeness centrality by inspecting the <strong>mean</strong>. The average closeness is an important property of a network. <em>Why? What does a network with a high average closeness look like? A low average closeness?</em></p>
<p>The mean closeness for an undirected network is:</p>
<p><span class="math display">\[\bar C_C =  \dfrac{\sum\limits_{i=1}^g C_C(n_i)}{g}\]</span></p>
<p>This equation, <span class="math inline">\(\dfrac{\sum\limits_{i=1}^g C_C(n_i)}{g}\)</span>, just says to sum up the closeness scores for each node and then divide by the number of nodes, <em>g</em>.</p>
<p>What is the mean closeness for our example network? We can pull these from the table above:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Node</th>
<th style="text-align: center;">Distance</th>
<th style="text-align: center;">Closeness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Jen</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">1/9 = 0.111</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tom</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">1/6 = 0.167</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Bob</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">1/5 = 0.200</td>
</tr>
<tr class="even">
<td style="text-align: center;">Leaf</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1/7 = 0.143</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Jim</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1/7 = 0.143</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\bar C_C =  \dfrac{\sum\limits_{i=1}^g C_C(n_i)}{g} = \dfrac{0.111 + 0.167 + 0.200 + 0.143 + 0.143}{5} = \dfrac{0.764}{5} = 0.153\]</span> The average closeness for this graph is 0.153. In other words, on average, a node has a closeness score of 0.153. But what does this mean?</p>
<p>One way to interpret this score is to convert the score to a distance. We can do this be taking 1 as the numerator and our mean closeness score as the denominator: <span class="math display">\[\dfrac{1}{0.153} = 6.536\]</span>, which tells us that the average node is 6.5 links away from all the other nodes in the graph.</p>
</section>
<section id="closeness-centralization" class="level3">
<h3 class="anchored" data-anchor-id="closeness-centralization">Closeness Centralization</h3>
<p>In the prior chapter we discussed <em>graph centralization</em>, which measures the extent to which the nodes in a network differ from one another in their individual centrality scores. Put differently, how much variation is there in the distribution of centrality scores? As with degree centralization, we can calculate the closeness centralization of the graph. A key difference, however, is that for closeness centralization, we use the standardized closeness score.</p>
<p>We can calculate closeness centralization as:</p>
<p><span class="math display">\[C_C = \frac{\sum\limits_{i=1}^g[C'_C(n^*)-C'_C(n_i)]}{[(g-2)(g-1)]/(2g-3)}\]</span> This may look imposing, but we can decompose it to see what it is doing:</p>
<ul>
<li><span class="math inline">\(C'_C(n^*)\)</span> is the largest standardized closeness score</li>
<li><span class="math inline">\(C'_C(n_i)\)</span> is the standardized closeness score for node <em>i</em></li>
<li><span class="math inline">\(\sum\limits_{i=1}^g[C'_C(n^*)-C'_C(n_i)]\)</span> simply takes the sum of deviations for each node from the largest value</li>
<li>Finally, we take that sum and divide it by <span class="math inline">\([(g-2)(g-1)]/(2g-3)\)</span></li>
</ul>
<p>If I lost you in some of the math, don’t worry. Let’s calculate the closeness centralization score for our example graph:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Recall our table of standardized closeness scores:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Node</th>
<th style="text-align: center;">Distance</th>
<th style="text-align: center;">Closeness</th>
<th style="text-align: center;">Standardized Closeness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Jen</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">1/9 = 0.111</td>
<td style="text-align: center;">0.111*4 = 0.444</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tom</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">1/6 = 0.167</td>
<td style="text-align: center;">0.167*4 = 0.668</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Bob</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">1/5 = 0.200</td>
<td style="text-align: center;">0.200*4 = 0.800</td>
</tr>
<tr class="even">
<td style="text-align: center;">Leaf</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1/7 = 0.143</td>
<td style="text-align: center;">0.143*4 = 0.572</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Jim</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1/7 = 0.143</td>
<td style="text-align: center;">0.143*4 = 0.572</td>
</tr>
</tbody>
</table>
<p><em>What is the largest standardized closeness score?</em> It is 0.8 for Bob. Also, we have <span class="math inline">\(g = 5\)</span>. Now, we just plug these into our equation:</p>
<p><span class="math display">\[C_C = \frac{\sum\limits_{i=1}^g[0.800-C'_C(n_i)]}{[(5-2)(5-1)]/(2*5-3)}\]</span></p>
<table class="table">
<colgroup>
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Node</th>
<th style="text-align: center;">Distance</th>
<th style="text-align: center;">Closeness</th>
<th style="text-align: center;">Standardized Closeness</th>
<th style="text-align: center;">Deviations of Standardized Closeness <span class="math inline">\(0.800-C'_C(n_i)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Jen</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">1/9 = 0.111</td>
<td style="text-align: center;">0.111*4 = 0.444</td>
<td style="text-align: center;">0.800 - 0.444 = 0.356</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tom</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">1/6 = 0.167</td>
<td style="text-align: center;">0.167*4 = 0.668</td>
<td style="text-align: center;">0.800 - 0.668 = 0.132</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Bob</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">1/5 = 0.200</td>
<td style="text-align: center;">0.200*4 = 0.800</td>
<td style="text-align: center;">0.800 - 0.800 = 0.000</td>
</tr>
<tr class="even">
<td style="text-align: center;">Leaf</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1/7 = 0.143</td>
<td style="text-align: center;">0.143*4 = 0.572</td>
<td style="text-align: center;">0.800 - 0.572 = 0.228</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Jim</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1/7 = 0.143</td>
<td style="text-align: center;">0.143*4 = 0.572</td>
<td style="text-align: center;">0.800 - 0.572 = 0.228</td>
</tr>
</tbody>
</table>
<p>Now, if we total all of the values in the last column we get 0.944. Plugging this in as our numerator, we get:</p>
<p><span class="math display">\[C_C = \frac{0.944}{[(5-2)(5-1)]/(2*5-3)} = \frac{0.944}{1.714} = 0.5507585 \approx 0.551\]</span></p>
<p>So, the closeness centralization score for our example graph is 0.551. <em>What does this mean?</em></p>
<p>When closeness centrality is evenly dispersed, meaning that all nodes have the same closeness score, then the numerator in the equation will be zero and the quotient will be close to 0. When there is considerable inequality in the closeness centrality scores between nodes, the quotient will be closer to 1. Thus, closer to 1 indicates that the graph is hierarchically structured and closer to 0 means that the graph is more decentralized.</p>
<p>We can see this by examining two additional undirected networks:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>The closeness centralization score for the figure on the left is 1, whereas the closeness centralization score for the figure on the right is 0.</p>
</section>
</section>
<section id="directed-graphs" class="level2">
<h2 class="anchored" data-anchor-id="directed-graphs">Directed Graphs</h2>
<p>As was covered in the prior chapter, when we have a directed graph, we have to consider directionality when evaluating a centrality measure. For example, in the graph below, <em>how far is Jen from Tom?</em> <em>How far is Jen from Bob?</em></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>To answer this question, let’s think again about what closeness measures. It is the inverse of the distance matrix. So, if we are looking at outgoing ties (i.e.&nbsp;<span class="math inline">\(L(n_i,n_j)\)</span>) then our equation is the same for the undirected graph:</p>
<p><span class="math display">\[C_C(n_i) = [\sum\limits_{j=1}^g d(n_i,n_j)]^{-1} = \frac{1}{[\sum\limits_{j=1}^g d(n_i,n_j)]}\]</span></p>
<p>Note, however, that the distance of <em>i</em> to <em>j</em>, <span class="math inline">\(d(n_i,n_j)\)</span>, does not necessarily equal the distance from <em>j</em> to <em>i</em>, <span class="math inline">\(d(n_j,n_i)\)</span>. For example, the distance from Jen to Tom, <span class="math inline">\(d(Jen,Tom)\)</span>, is 1. But, the distance from Tom to Jen, <span class="math inline">\(d(Tom,Jen)\)</span> is….? It is <u>undefined</u> because there is not an edge that originates from Tom and ends at Jen. This complicates things a bit. Let’s work through an example to see what this looks like.</p>
<section id="outdegree" class="level3">
<h3 class="anchored" data-anchor-id="outdegree">Outdegree</h3>
<p>Closeness centrality in directed graphs usually focuses on the send network (i.e.&nbsp;outgoing ties). Remember, <em>row</em> sums are the <em>outdegree</em>, so row distance tells you how close <u>you</u> are to others. That is, how many steps it takes <u>you</u> to reach another node.</p>
<p>As before, we want to first build a <em>distance matrix</em> which shows the value of the geodesic (i.e.&nbsp;shortest path) from <em>i</em> to <em>j</em>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p><em>How far is Jen from Tom?</em> <em>How far is Jen from Bob?</em> To figure this out, we can simply count the steps from Jen to Tom. Then Jen to Bob.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Jen is 1 step from Tom and 2 steps from Bob. <em>What about the rest of the scores for Jen?</em></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Now, recall that we sum these distances, and then take the reciprocal:</p>
<p><span class="math display">\[C_C(Jen) =  \frac{1}{[\sum\limits_{j=1}^g d(Jen,n_j)]} = \frac{1}{9} = 0.111\]</span></p>
<p><em>What about Bob? How far is Bob from everyone?</em></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>How far is Bob from Jen? Bob, is “infinite distance” from Jen because there is not a directed path by which he can reach her. This is also the case for the distance from Bob to Tom. But, Bob does have directed ties to Jim and Leaf. With directionality in mind, they are unreachable. But, Bob is 1 step from Leaf and 1 step from Jim along a directed path:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>So what is Bob’s closeness centrality score? If we do not count the cells that have “infinite distance”, and only count cells where there are values, then we just count the distance for Leaf and Jim, which sums to 2. We just plug this in:</p>
<p><span class="math display">\[C_C(Bob) =  \frac{1}{[\sum\limits_{j=1}^g d(Bob,n_j)]} = \frac{1}{2} = 0.500\]</span></p>
<p>Note that this changes the denominator for each node.</p>
<p>If we fill in our matrix, then we have the following distance values:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Going through the rest of the matrix, we get a closeness centrality score for each individual:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Node</th>
<th style="text-align: center;">Distance</th>
<th style="text-align: center;">Closeness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Jen</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">1/9 = 0.111</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tom</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">1/5 = 0.200</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Bob</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1/2 = 0.500</td>
</tr>
<tr class="even">
<td style="text-align: center;">Leaf</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1/2 = 0.500</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Jim</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1/2 = 0.500</td>
</tr>
</tbody>
</table>
<section id="standardization-1" class="level4">
<h4 class="anchored" data-anchor-id="standardization-1">Standardization</h4>
<p>Don’t forget: raw centrality scores are sensitive to the size of the graph. So, as before, we can standardize our closeness score as:</p>
<p><span class="math display">\[C'_C(n_i) = [\sum\limits_{j=1}^g d(n_i,n_j)]^{-1} \times [g-1]\]</span></p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Node</th>
<th style="text-align: center;">Distance</th>
<th style="text-align: center;">Closeness</th>
<th style="text-align: center;">Standardized Closeness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Jen</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">1/9 = 0.111</td>
<td style="text-align: center;">0.111*4 = 0.444</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tom</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">1/5 = 0.200</td>
<td style="text-align: center;">0.200*4 = 0.800</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Bob</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1/2 = 0.500</td>
<td style="text-align: center;">0.500*4 = 0.200</td>
</tr>
<tr class="even">
<td style="text-align: center;">Leaf</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1/2 = 0.500</td>
<td style="text-align: center;">0.500*4 = 0.200</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Jim</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1/2 = 0.500</td>
<td style="text-align: center;">0.500*4 = 0.200</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="mean-clonessness" class="level3">
<h3 class="anchored" data-anchor-id="mean-clonessness">Mean Clonessness</h3>
<p>As we did above for an undirected graph, we can examine the average closeness for a directed graph, as this is an important property of a network. <em>Why? What does a network with a high average closeness look like? A low average closeness?</em></p>
<p>The mean closeness for an directed network is:</p>
<p><span class="math display">\[\bar C_C =  \dfrac{\sum\limits_{i=1}^g C_C(n_i)}{g}\]</span></p>
<p>This equation, <span class="math inline">\(\dfrac{\sum\limits_{i=1}^g C_C(n_i)}{g}\)</span>, just says to sum up the closeness scores for each node and then divide by the number of nodes, <em>g</em>.</p>
<p>What is the mean closeness for our example network? We can pull these from the table above:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Node</th>
<th style="text-align: center;">Distance</th>
<th style="text-align: center;">Closeness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Jen</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">1/9 = 0.111</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tom</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">1/5 = 0.200</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Bob</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1/2 = 0.500</td>
</tr>
<tr class="even">
<td style="text-align: center;">Leaf</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1/2 = 0.500</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Jim</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1/2 = 0.500</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\bar C_C =  \dfrac{\sum\limits_{i=1}^g C_C(n_i)}{g} = \dfrac{0.111 + 0.200 + 0.500 + 0.500 + 0.500}{5} = \dfrac{1.811}{5} = 0.362\]</span> The average closeness for this graph is 0.362. In other words, on average, a node has a closeness score of 0.362. But what does this mean?</p>
<p>Again, one way to interpret this score is to convert the score to a distance. We can do this be taking 1 as the numerator and our mean closeness score as the denominator: <span class="math display">\[\dfrac{1}{0.362} = 2.762\]</span>, which tells us that the average node is nearly links away from all the other nodes in the graph.</p>
</section>
<section id="indegree" class="level3">
<h3 class="anchored" data-anchor-id="indegree">Indegree</h3>
<p>Note that in the prior section we were looking at <em>outdegree</em>. When we are looking at <em>outgoing</em> ties the closeness scores reflect how close <u>you</u> are to other nodes. For example, Tom’s distance to Leaf is 2, meaning that it takes 2 outgoing ties to reach Leaf. What about the other way around? We can reverse this and look at the <em>incoming</em> ties by focusing on <em>indegree</em>. Remember, <em>column</em> sums are the <em>indegree</em>, so column distance tells you how close <u>others</u> are to you. That is, how many steps it takes a <u>node</u> to reach you. The difference is a bit nuanced, but meaningful. In this case, instead of summing the rows as we did above, we could sum the columns.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>If we sum the columns, then we get these scores:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Node</th>
<th style="text-align: center;">Distance</th>
<th style="text-align: center;">Closeness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Jen</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1/0 = Undefined</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tom</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1/1 = 1.000</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Bob</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">1/5 = 0.200</td>
</tr>
<tr class="even">
<td style="text-align: center;">Leaf</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1/7 = 0.143</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Jim</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1/7 = 0.143</td>
</tr>
</tbody>
</table>
<section id="standardization-2" class="level4">
<h4 class="anchored" data-anchor-id="standardization-2">Standardization</h4>
<p>We can then standardize our closeness score as:</p>
<p><span class="math display">\[C'_C(n_i) = [\sum\limits_{j=1}^g d(n_i,n_j)]^{-1} \times [g-1]\]</span></p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Node</th>
<th style="text-align: center;">Distance</th>
<th style="text-align: center;">Closeness</th>
<th style="text-align: center;">Standardized Closeness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Jen</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1/0 = Undefined</td>
<td style="text-align: center;">Undefined*4 = Undefined</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tom</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1/1 = 1.000</td>
<td style="text-align: center;">1.000*4 = 4.000</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Bob</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">1/5 = 0.200</td>
<td style="text-align: center;">0.200*4 = 0.800</td>
</tr>
<tr class="even">
<td style="text-align: center;">Leaf</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1/7 = 0.143</td>
<td style="text-align: center;">0.143*4 = 0.571</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Jim</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1/7 = 0.143</td>
<td style="text-align: center;">0.143*4 = 0.571</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="conversion-to-undirected-graph" class="level3">
<h3 class="anchored" data-anchor-id="conversion-to-undirected-graph">Conversion to Undirected Graph</h3>
<p><strong>NOTE</strong>: While these are correct, mathematically, they are far less intuitive than the scores we calculated based on the <em>outgoing</em> ties. For example, Tom’s closeness score is 1. But, Bob, Leaf, and Jim cannot reach him. Also, note that Tom’s standardized score is greater than 1. For these reasons, we often convert the directed graph to an undirected graph and calculate the scores on the undirected graph. In this case, the directed graph we have here would revert to the undirected graph we examined above in the section on undirected graphs.</p>
</section>
<section id="closeness-centralization-1" class="level3">
<h3 class="anchored" data-anchor-id="closeness-centralization-1">Closeness Centralization</h3>
<p>The denominator for group closeness centralization is not defined for directed graphs. To get a centralization score, we would just convert it to an undirected graph and calculate the score. Note that, unlike with degree centralization which has two scores (i.e.&nbsp;indegree centralization and outdegree centralization), there is only a single centralization score for a directed graph.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="snaca-centrality-closeness_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>For the graph above, we can compare the centralization scores based on the different measures of centrality. The indegree centralization score is 0.428, the outdegree centralization score is 0.125, and the closeness centralization score is 0.556. What can we say about the closeness centralization scores for each type of centrality?</p>
<p><br></p>
</section>
</section>
<section id="test-your-knowledge" class="level2">
<h2 class="anchored" data-anchor-id="test-your-knowledge">Test your Knowledge</h2>
<ul>
<li>What does “closeness centrality” measure in a network?</li>
<li>How does closeness centrality differ from degree centrality when analyzing a network?</li>
<li>Explain why individuals with high closeness centrality might hold important roles within a network, even if they are not directly connected to many others.</li>
<li>Describe a scenario in which using closeness centrality would be more informative for a crime analyst than using degree centrality.</li>
<li>How is the calculation of closeness centrality different in directed graphs compared to undirected graphs?</li>
<li>How does the closeness centralization score help in determining the overall structure of a network?</li>
<li>What does it mean if the closeness centralization score of a graph is close to 1? What does it mean if the score is close to 0?</li>
</ul>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>In this chapter we focused on closeness centrality. This concept is particularly useful for understanding the efficiency of information flow in a network. Unlike degree centrality, which measures direct connections, closeness centrality provides insight into the influence and access a node has through indirect connections. Studies, such as the analysis of drug trafficking and terrorist networks, have shown that individuals with high closeness centrality, though not necessarily the most directly connected, play crucial roles in maintaining communication and operational efficiency. In the next chapter we will focus on a final conceptualization and operationalization of centrality: <em>betweenness</em>.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-bright2015illuminating" class="csl-entry" role="listitem">
Bright, David A., Caitlin E. Hughes, and Jennifer Chalmers. 2015. <span>“Illuminating Dark Networks: A Social Network Analysis of an Australian Drug Trafficking Syndicate.”</span> <em>Crime, Law and Social Change</em> 63 (1-2): 63–78.
</div>
<div id="ref-sageman2004understanding" class="csl-entry" role="listitem">
Sageman, Marc. 2004. <em>Understanding Terror Networks</em>. University of Pennsylvania Press.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./snaca-centrality-degree.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Degree Centrality</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./snaca-centrality-betweenness.html" class="pagination-link">
        <span class="nav-page-text">Betweenness Centrality</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Social Network Analysis for Crime Analysts was written by <a href="https://jacobtnyoung.github.io/">Jacob T.N. Young</a></div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>